#!/bin/bash

# start with a pithy quote
cat etc/quotes | gawk '
   BEGIN {srand('$RANDOM')
          FS="\n"; RS=""} 
   NR==1 {print "\n"$0"\n"; next}
         {a[rand()] = $0} 
   END   {for(i in a){print a[i]; exit}}' 

################
dirsWithPython() {
  for x in $(find . -name '*.py' |grep -v \.git);do
      dirname $x
  done | sort | uniq
}
# may file on pathname with spaces
fullname() {  (cd "$1";  pwd; ) }

path=""
for x in $(dirsWithPython); do
    if [ -z "$path" ]; then
	path="$(fullname "$x")"
    else
	path="$path:$(fullname "$x")"
    fi
done

py="PYTHONPATH='$path' /usr/bin/python -B "
alias python="$py "

##################
if [ "etc/gitignore" -nt ".gitignore" ]; then
    cp etc/gitignore .gitignore
    git add .gitignore
fi

##################
watch() {
    rerun "$py $1.py"
}
