#!/bib/bash

quote() {
     cat - | gawk 'BEGIN {srand('$RANDOM')
                          FS="\n"; RS=""} 
                   NR==1 {print "\n"$0"\n"; next}
                         {a[rand()]=$0} 
                   END   {for(i in a){print a[i]; exit}}'
}
cat<<'EOF' | quote

        _,..---..,_       Welcome to Pie, v1.0
    ,-"`    .'.    `"-,   (Timm's tricks for a command-line
   ((      '.'.'      ))   IDE for Python for *Nix/Bash.)
    `'-.,_   '   _,.-'`    
jgs   `\  `"""""`  /`     
        `""-----""`       

"In the pie chart of my brain growing up, 
there's a huge slice for 'Ghostbusters.'"
-- Evan Goldberg

"The older I get, the more I become an apple 
pie, sparkling cider kind of guy."
-- Scott Foley

"You can't imagine what satisfaction can be 
gotten from throwing a pie into someone's face."
-- Emma Thompson

"If you wish to make an apple pie from scratch, 
you must first invent the universe."
-- Carl Sagan

"So the pie isn't perfect? Cut it into wedges. 
Stay in control, and never panic."
-- Martha Stewart

"I'm from Maine. I eat apple pie for breakfast."
-- Rachel Nichols

"You can't carve up the world. It's not a pie."
-- Patti Smith
EOF

################
dirsWithPython() {
  for x in $(find . -name '*.py' |grep -v \.git);do
      dirname $x
  done | sort | uniq
}
# may file on pathname with spaces
fullname() {  (cd "$1";  pwd; ) }

path=""
for x in $(dirsWithPython); do
    if [ -z "$path" ]; then
	path="$(fullname "$x")"
    else
	path="$path:$(fullname "$x")"
    fi
done

py="PYTHONPATH='$path' /usr/bin/python -B "
alias python="$py "

##################
if [ "etc/gitignore" -nt ".gitignore" ]; then
    cp etc/gitignore .gitignore
    git add .gitignore
fi

##################
watch() {
    rerun "$py $1.py"
}
