#!/bib/bash

cat <<'EOF'

        _,..---..,_       Welcome to Pie, v1.0
    ,-"`    .'.    `"-,   (Timm's tricks for a command-line
   ((      '.'.'      ))   IDE for Python (in *Nix/Bash).)
    `'-.,_   '   _,.-'`    
jgs   `\  `"""""`  /`     
        `""-----""`       

 "Pie is a dish best served cold (not). 
  Simple is better than complex.
  Now is better than never.
  If the implementation is hard to explain, it's a bad idea.
  If the implementation is easy to explain, it may be a good idea."

EOF

################
dirsWithPython() {
  for x in $(find . -name '*.py' |grep -v \.git);do
      dirname $x
  done | sort | uniq
}
# may file on pathname with spaces
fullname() {  (cd "$1";  pwd; ) }

path=""
for x in $(dirsWithPython); do
    if [ -z "$path" ]; then
	path="$(fullname "$x")"
    else
	path="$path:$(fullname "$x")"
    fi
done

py="PYTHONPATH='$path' /usr/bin/python -B3 "
alias python="$py "

##################
if [ "etc/gitignore" -nt ".gitignore" ]; then
    cp etc/gitignore .gitignore
    git add .gitignore
fi

##################
watch() {
    rerun "$py $1.py"
}
